// Let goreportcard check us.
// Code generated by gen_version; DO NOT EDIT.

package gostwire

// SemVersion is the semantic version string of the ghostwire module.
const SemVersion = "2.3.0-4-g1927622"
