// Let goreportcard check us.
// Code generated by gen_version; DO NOT EDIT.

package gostwire

// SemVersion is the semantic version string of the gostwire module.
const SemVersion = "2.1.4-26-g80ab126"
