// Let goreportcard check us.
// Code generated by gen_version; DO NOT EDIT.

package gostwire

// SemVersion is the semantic version string of the ghostwire module.
const SemVersion = "0.9.1-4-g368ef35"
