// autogenerated from icon svg file "icons/containeestates/Capable.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const CapableIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M6.355 2.9l-.287.737S3.176 10.97 3 17.975l-.018.675.623.268C7.251 20.487 8.902 21 12 21c2.633 0 4.63-.521 6.066-1.395 1.437-.873 2.298-2.125 2.541-3.421.486-2.593-1.572-5.182-4.603-5.184-3.949-.038-5.87 2.307-6.395 3H9V7h1.705l1.188-3.326L6.355 2.9zM7 7.283V16h3.547l.295-.459S12.45 12.963 15.99 13H16c1.967 0 2.906 1.41 2.643 2.816-.132.704-.584 1.452-1.616 2.079C15.996 18.52 14.367 19 12 19c-2.66 0-3.98-.415-6.926-1.66C5.29 13.212 6.211 9.75 7 7.283z" fontWeight={400} fontFamily="sans-serif" /></SvgIcon>;
export default CapableIcon;