// autogenerated from icon svg file "icons/containeestates/IEAppDebuggableState.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const IEAppDebuggableStateIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="m6.6 1.44-.82.83 2.1 2.1A7 7 0 0 0 5.298 8H2v2h3v2H2v2h3v2H2v2h3.291c.86 2.893 3.534 5 6.709 5a6.995 6.995 0 0 0 6.709-5H22v-2h-3v-2h3v-2h-3v-2h3V8h-3.297a7 7 0 0 0-2.584-3.63l2.102-2.1-.82-.83L15.1 3.75C14.16 3.28 13.12 3 12 3s-2.16.28-3.09.75zM12 5a5 5 0 0 1 5 5H7a5 5 0 0 1 5-5m-2 2a1 1 0 0 0-1 1 1 1 0 0 0 1 1 1 1 0 0 0 1-1 1 1 0 0 0-1-1m4 0a1 1 0 0 0-1 1 1 1 0 0 0 1 1 1 1 0 0 0 1-1 1 1 0 0 0-1-1m-7 4h10v5a5 5 0 0 1-5 5 5 5 0 0 1-5-5zm5 2-3 3 3 3 3-3z" /></SvgIcon>;
export default IEAppDebuggableStateIcon;