// autogenerated from icon svg file "icons/containeestates/PausedState.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const PausedStateIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2H5zm0 2h14v14H5V5zm3 3v8h3V8H8zm5 0v8h3V8h-3z" /></SvgIcon>;
export default PausedStateIcon;