// autogenerated from icon svg file "icons/containeestates/Privileged.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const PrivilegedIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 16 3 5l5.5 5L12 4l3.5 6L21 5l-2 11zm14 3c0 .6-.4 1-1 1H6c-.6 0-1-.4-1-1v-1h14z" /></SvgIcon>;
export default PrivilegedIcon;