// autogenerated from icon svg file "icons/containeestates/RunningState.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const RunningStateIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 2h14v14H5zm4 3v8l6-4z" /></SvgIcon>;
export default RunningStateIcon;