// autogenerated from icon svg file "icons/containeestates/StoppedState.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const StoppedStateIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 2h14v14H5zm3 3v8h8V8z" /></SvgIcon>;
export default StoppedStateIcon;