// autogenerated from icon svg file "icons/addresses/Ipv4Address.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const Ipv4AddressIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2H5zm0 2h14v14H5V5zm4 2v6h4v4h2V7h-2v4h-2V7H9z" /></SvgIcon>;
export default Ipv4AddressIcon;