// autogenerated from icon svg file "icons/addresses/Ipv6Address.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const Ipv6AddressIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 2h14v14H5zm6 2a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2a2 2 0 0 0 2-2v-2a2 2 0 0 0-2-2h-2V9h4V7zm0 6h2v2h-2z" /></SvgIcon>;
export default Ipv6AddressIcon;