// autogenerated from icon svg file "icons/addresses/MacAddress.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const MacAddressIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 2h14v14H5zm2 2v10h2v-6.662L10.992 13h2.016L15 10.338V17h2V7h-2l-3 4.008L9 7z" /></SvgIcon>;
export default MacAddressIcon;