// autogenerated from icon svg file "icons/nifs/BridgeInternal.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const BridgeInternalIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M18.5 2A2.5 2.5 0 0 0 16 4.5V5c-.55 0-1 .45-1 1v4c0 .55.45 1 1 1h5c.55 0 1-.45 1-1V6c0-.55-.45-1-1-1v-.5A2.5 2.5 0 0 0 18.5 2m0 1c.83 0 1.5.67 1.5 1.5V5h-3v-.5c0-.83.67-1.5 1.5-1.5M2 10v12h3v-2c0-4 3-6 7-6s7 2 7 6v2h3v-9h-6.334H15h-.666A1.33 1.33 0 0 1 13 11.666v-1.332c0-.116.02-.227.047-.334z" /></SvgIcon>;
export default BridgeInternalIcon;