// autogenerated from icon svg file "icons/nifs/Bridge.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const BridgeIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M2 6v12h3v-2c0-4 3-6 7-6s7 2 7 6v2h3V6z" /></SvgIcon>;
export default BridgeIcon;