// autogenerated from icon svg file "icons/nifs/Dummy.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const DummyIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 6v13h14V6Zm1 1h12v11h-5v-7h3V9H8v2h3v7H6Z" /></SvgIcon>;
export default DummyIcon;