// autogenerated from icon svg file "icons/nifs/HardwareNicPF.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const HardwareNicPFIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M7 4.5c-.554 0-1 .446-1 1v2H4v2H3c-.554 0-1 .446-1 1s.446 1 1 1h1v2h2v2c0 .554.446 1 1 1h4v2c0 .554.446 1 1 1h7c.554 0 1-.446 1-1v-2h1c.554 0 1-.446 1-1v-10c0-.554-.446-1-1-1H7zm1 2h12v8h-1a.998.998 0 00-1 1v2h-1V16a.499.499 0 10-1 0v1.5h-1V16a.499.499 0 10-1 0v1.5h-1v-2c0-.554-.446-1-1-1H8v-1h2v-6H8v-1zM13 8v5h1v-1h1a2 2 0 000-4h-2zm1 1h1a1 1 0 110 2h-1V9zm-7 .5h2v2H7v-2z" /></SvgIcon>;
export default HardwareNicPFIcon;