// autogenerated from icon svg file "icons/nifs/HardwareNic.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const HardwareNicIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M7 4.5c-.554 0-1 .446-1 1v2H4v2H3c-.554 0-1 .446-1 1s.446 1 1 1h1v2h2v2c0 .554.446 1 1 1h4v2c0 .554.446 1 1 1h7c.554 0 1-.446 1-1v-2h1c.554 0 1-.446 1-1v-10c0-.554-.446-1-1-1zm1 2h12v8h-1a1 1 0 0 0-1 1v2h-1V16a.499.499 0 1 0-1 0v1.5h-1V16a.499.499 0 1 0-1 0v1.5h-1v-2c0-.554-.446-1-1-1H8v-1h2v-6H8zm6 2v4h4v-4zm-7 1h2v2H7z" /></SvgIcon>;
export default HardwareNicIcon;