// autogenerated from icon svg file "icons/nifs/HardwareNicVF.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const HardwareNicVFIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M7 4.5c-.554 0-1 .446-1 1v2H4v2H3c-.554 0-1 .446-1 1s.446 1 1 1h1v2h2v2c0 .554.446 1 1 1h4v2c0 .554.446 1 1 1h7c.554 0 1-.446 1-1v-2h1c.554 0 1-.446 1-1v-10c0-.554-.446-1-1-1zm1 2h12v8h-1a.998.998 0 00-1 1v2h-1V16a.499.499 0 10-1 0v1.5h-1V16a.499.499 0 10-1 0v1.5h-1v-2c0-.554-.446-1-1-1H8v-1h2v-6H8zm-1 3h2v2H7zM13 8l2 5h1l2-5h-1l-1.5 3.75L14 8z" /></SvgIcon>;
export default HardwareNicVFIcon;