// autogenerated from icon svg file "icons/nifs/Macvlan.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const MacvlanIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M7 4.5c-.554 0-1 .446-1 1v2H4v2H3c-.554 0-1 .446-1 1s.446 1 1 1h1v2h2v2c0 .554.446 1 1 1h2v-2H8v-1h2v-6H8v-1h1v-2H7zm4 0v2h2v-2h-2zm4 0v2h2v-2h-2zm4 0v2h1V8h2V5.5c0-.554-.446-1-1-1h-2zm-12 5h2v2H7v-2zm13 .5v2h2v-2h-2zm0 4v.5h-1a.998.998 0 00-1 1v1h3c.554 0 1-.446 1-1V14h-2zm-9 .5v2h2v-1c0-.554-.446-1-1-1h-1zm0 3v1c0 .554.446 1 1 1h1v-2h-2zm4 0v2h1v-2h-1zm3 0v2h1c.554 0 1-.446 1-1v-1h-2z" /></SvgIcon>;
export default MacvlanIcon;