// autogenerated from icon svg file "icons/nifs/Macvlan.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const MacvlanIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M7 4.5c-.554 0-1 .446-1 1v2H4v2H3c-.554 0-1 .446-1 1s.446 1 1 1h1v2h2v2c0 .554.446 1 1 1h2v-2H8v-1h2v-6H8v-1h1v-2zm4 0v2h2v-2zm4 0v2h2v-2zm4 0v2h1V8h2V5.5c0-.554-.446-1-1-1zm-12 5h2v2H7zm13 .5v2h2v-2zm0 4v.5h-1a1 1 0 0 0-1 1v1h3c.554 0 1-.446 1-1V14zm-9 .5v2h2v-1c0-.554-.446-1-1-1zm0 3v1c0 .554.446 1 1 1h1v-2zm4 0v2h1v-2zm3 0v2h1c.554 0 1-.446 1-1v-1z" /></SvgIcon>;
export default MacvlanIcon;