// autogenerated from icon svg file "icons/nifs/MacvlanMaster.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const MacvlanMasterIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M9 5v6h2v9c0 .554.446 1 1 1s1-.446 1-1v-9h2V5H9zm2 1h2v2.852h-2V6zm4 7a1 1 0 00-1 1 1 1 0 001 1 1 1 0 001-1 1 1 0 00-1-1zm3 0a1 1 0 00-1 1 1 1 0 001 1 1 1 0 001-1 1 1 0 00-1-1zM6 16a1 1 0 00-1 1 1 1 0 001 1 1 1 0 001-1 1 1 0 00-1-1zm3 0a1 1 0 00-1 1 1 1 0 001 1 1 1 0 001-1 1 1 0 00-1-1z" /></SvgIcon>;
export default MacvlanMasterIcon;