// autogenerated from icon svg file "icons/nifs/Nic.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const NicIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M9 6v6h2v7c0 .554.446 1 1 1s1-.446 1-1v-7h2V6H9zm2 1h2v2.852h-2V7z" /></SvgIcon>;
export default NicIcon;