// autogenerated from icon svg file "icons/nifs/Overlay.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const OverlayIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M8 4.125a3 3 0 0 0-3 3 3 3 0 0 0 2.25 2.903v3.097H2v3h21v-3h-5.25v-3.1a3 3 0 0 0 2.25-2.9 3 3 0 0 0-3-3 3 3 0 0 0-3 3 3 3 0 0 0 2.25 2.903v3.097h-7.5v-3.1a3 3 0 0 0 2.25-2.9 3 3 0 0 0-3-3m0 1.5a1.5 1.5 0 0 1 1.5 1.5 1.5 1.5 0 0 1-1.5 1.5 1.5 1.5 0 0 1-1.5-1.5 1.5 1.5 0 0 1 1.5-1.5m9 0a1.5 1.5 0 0 1 1.5 1.5 1.5 1.5 0 0 1-1.5 1.5 1.5 1.5 0 0 1-1.5-1.5 1.5 1.5 0 0 1 1.5-1.5M2.75 18.375v1.5h1.5v-1.5zm3 0v1.5h1.5v-1.5zm3 0v1.5h1.5v-1.5zm3 0v1.5h1.5v-1.5zm3 0v1.5h1.5v-1.5zm3 0v1.5h1.5v-1.5zm3 0v1.5h1.5v-1.5z" /></SvgIcon>;
export default OverlayIcon;