// autogenerated from icon svg file "icons/nifs/Tap.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const TapIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M14.953 2.635c-.101.002-.21.016-.33.045L3 6v2h5V6l7-2c1.042-.298.931-1.388-.047-1.365zM3 9v12h5v-8l9-1c0-1-1-2-2-2H8V9z" /><path d="M17 13l-2 .223V15h-2v6h6v-6h-2zm-2 4.148h2V20h-2z" /></SvgIcon>;
export default TapIcon;