// autogenerated from icon svg file "icons/nifs/Tun.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const TunIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 4a9 9 0 00-9 9v6h18v-6a9 9 0 00-9-9zm.5 1.018a8 8 0 013.12.847l-1.136 1.676a6 6 0 00-1.984-.518zm-1 .015v2.002a6 6 0 00-1.986.506l-1.125-1.66a8 8 0 013.111-.848zm4.982 1.342A8 8 0 0118.62 8.51l-1.8.916A6 6 0 0015.36 8.03zm-8.957.014l1.118 1.65a6 6 0 00-1.448 1.39l-1.799-.915a8 8 0 012.13-2.125zM19.13 9.37A8 8 0 0119.936 12h-2.022a6 6 0 00-.568-1.72zm-14.242.006l1.779.906A6 6 0 006.092 12H4.064a8 8 0 01.823-2.623zM4 13h2v2H4zm14 0h2v2h-2zM4 16h2v2H4zm14 0h2v2h-2z" /></SvgIcon>;
export default TunIcon;