// autogenerated from icon svg file "icons/nifs/Tun.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const TunIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 4a9 9 0 0 0-9 9v6h18v-6a9 9 0 0 0-9-9m.5 1.018a8 8 0 0 1 3.12.847l-1.136 1.676a6 6 0 0 0-1.984-.518Zm-1 .015v2.002a6 6 0 0 0-1.986.506l-1.125-1.66a8 8 0 0 1 3.111-.848m4.982 1.342A8 8 0 0 1 18.62 8.51l-1.8.916A6 6 0 0 0 15.36 8.03Zm-8.957.014 1.118 1.65a6 6 0 0 0-1.448 1.39l-1.799-.915a8 8 0 0 1 2.13-2.125M19.13 9.37A8 8 0 0 1 19.936 12h-2.022a6 6 0 0 0-.568-1.72Zm-14.242.006 1.779.906A6 6 0 0 0 6.092 12H4.064a8 8 0 0 1 .823-2.623M4 13h2v2H4Zm14 0h2v2h-2ZM4 16h2v2H4Zm14 0h2v2h-2z" /></SvgIcon>;
export default TunIcon;