// autogenerated from icon svg file "icons/nifs/Veth.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const VethIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M2 9v6h6v-2h1a1 1 0 00.447-.105l1.356-.678 1.49 1.49a1 1 0 001.154.188l1.79-.895H16v2h6V9h-6v2h-1a1 1 0 00-.447.105l-1.356.678-1.49-1.49a1 1 0 00-.678-.293 1 1 0 00-.476.105L8.763 11H8V9H2zm1 2h2.852v2H3v-2zm15.148 0H21v2h-2.852v-2z" /></SvgIcon>;
export default VethIcon;