// autogenerated from icon svg file "icons/portstates/Connected.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const ConnectedIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 9a3 3 0 00-3 3 3 3 0 003 3 3 3 0 002.826-2h8.35A3 3 0 0019 15a3 3 0 003-3 3 3 0 00-3-3 3 3 0 00-2.826 2h-8.35A3 3 0 005 9zm0 2a1 1 0 011 1 1 1 0 01-1 1 1 1 0 01-1-1 1 1 0 011-1zm14 0a1 1 0 011 1 1 1 0 01-1 1 1 1 0 01-1-1 1 1 0 011-1z" /></SvgIcon>;
export default ConnectedIcon;