// autogenerated from icon svg file "icons/portstates/Connected.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const ConnectedIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 9a3 3 0 0 0-3 3 3 3 0 0 0 3 3 3 3 0 0 0 2.826-2h8.35A3 3 0 0 0 19 15a3 3 0 0 0 3-3 3 3 0 0 0-3-3 3 3 0 0 0-2.826 2h-8.35A3 3 0 0 0 5 9m0 2a1 1 0 0 1 1 1 1 1 0 0 1-1 1 1 1 0 0 1-1-1 1 1 0 0 1 1-1m14 0a1 1 0 0 1 1 1 1 1 0 0 1-1 1 1 1 0 0 1-1-1 1 1 0 0 1 1-1" /></SvgIcon>;
export default ConnectedIcon;