// autogenerated from icon svg file "icons/CaptureMulti.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const CaptureMultiIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12.854 5.012c-1.567.232-3.717 1.045-5.555 2.787S4 12.248 4 16a1 1 0 0 0 1 1 1 1 0 0 0 1-1c0-3.248 1.189-5.341 2.676-6.75C9.757 8.225 10.949 7.69 12 7.352v3.947c-1.182 1.67-2 3.893-2 6.701a1 1 0 0 0 1 1 1 1 0 0 0 1-1c0-3.248 1.189-5.341 2.676-6.75.996-.944 2.084-1.466 3.082-1.822-.72 3.346-.753 5.663.29 8.88a1 1 0 0 0 1.26.643 1 1 0 0 0 .643-1.26c-1.17-3.61-1.167-4.997.016-9.433a1 1 0 0 0-1.113-1.246c-1.372.203-3.19.853-4.854 2.18V6a1 1 0 0 0-1.146-.988" /></SvgIcon>;
export default CaptureMultiIcon;