// autogenerated from icon svg file "icons/CaptureCheck.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const CaptureCheckIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 3q-.824 0-1.412.588A1.93 1.93 0 0 0 3 5v14q0 .825.588 1.412Q4.175 21 5 21h14q.825 0 1.412-.588Q21 19.825 21 19V5q0-.824-.588-1.412A1.93 1.93 0 0 0 19 3zm0 2h14v14H5zm11.004 2a1 1 0 0 0-.15.012c-1.328.196-3.498.438-5.409 1.674S7 12.248 7 16a1 1 0 0 0 1 1 1 1 0 0 0 1-1c0-3.248 1.116-4.72 2.531-5.635.996-.644 2.157-.924 3.26-1.127-.576 2.793-.599 4.503.26 7.078a1 1 0 0 0 1.265.633 1 1 0 0 0 .633-1.265c-.979-2.937-.969-3.48.022-7.442A1 1 0 0 0 16.004 7" /></SvgIcon>;
export default CaptureCheckIcon;