// autogenerated from icon svg file "icons/CaptureOff.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const CaptureOffIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M3.516 3.516 2.1 4.93l6 6c-.526 1.17-.885 2.527-1.002 4.07H3v2h5a1 1 0 0 0 1-1c0-1.394.221-2.575.59-3.58l9.48 9.48 1.414-1.416L17 17l-2.43-2.43-4.015-4.015-1.422-1.422zm12.517 1.486a1 1 0 0 0-.18.01c-1.518.225-3.583.997-5.382 2.629l1.42 1.42c.936-.823 1.94-1.302 2.867-1.633-.317 1.472-.5 2.744-.518 3.982l2.205 2.205c-.516-2.241-.39-3.935.522-7.357a1 1 0 0 0-.934-1.256M17.83 15l2 2H21v-2z" /></SvgIcon>;
export default CaptureOffIcon;