// autogenerated from icon svg file "icons/CaptureMultiOn.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const CaptureMultiOnIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12.984 5q-.064 0-.13.012C9.479 5.512 4 8.659 4 16a1 1 0 0 0 1 1h5.037A14 14 0 0 0 10 18a1 1 0 0 0 1 1h8a1 1 0 0 0 .951-1.309c-1.17-3.61-1.167-4.997.016-9.433.5-1.886-3.69-1.484-6.793 1.656.13-1.007.393-2.155.793-3.656A1.002 1.002 0 0 0 12.984 5" /></SvgIcon>;
export default CaptureMultiOnIcon;