// autogenerated from icon svg file "icons/Capture.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const CaptureIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M15.854 5.012c-1.567.232-3.717 1.045-5.555 2.787C8.636 9.374 7.34 11.786 7.098 15H3v2h5a1 1 0 0 0 1-1c0-3.248 1.189-5.341 2.676-6.75.996-.944 2.084-1.466 3.082-1.822-.72 3.346-.753 5.663.29 8.88A1 1 0 0 0 16 17h5v-2h-4.186c-.909-3.035-.937-4.654.153-8.742a1 1 0 0 0-1.113-1.246" /></SvgIcon>;
export default CaptureIcon;