// autogenerated from icon svg file "icons/CaptureMultiOn.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const CaptureMultiOnIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M11.984 3q-.064 0-.13.012c-1.567.232-3.717 1.045-5.555 2.787S3 10.248 3 14a1 1 0 0 0 1 1h8l.03-.002C11.394 16.393 11 18.055 11 20a1 1 0 0 0 1 1h8a1 1 0 0 0 .951-1.309c-1.17-3.61-1.167-4.997.016-9.433a1 1 0 0 0-1.113-1.246c-1.567.232-3.717 1.045-5.555 2.787-.51.482-.988 1.041-1.416 1.674-1.098-3.445-1.074-4.872.084-9.215A1.002 1.002 0 0 0 11.984 3" /></SvgIcon>;
export default CaptureMultiOnIcon;