// autogenerated from icon svg file "icons/Case.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const CaseIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="m3.975 17 3.75-10h1.8l3.75 10H11.55l-.9-2.55H6.6L5.7 17Zm3.15-4h3l-1.45-4.15h-.1zm9.225 4.275q-1.225 0-1.925-.637-.7-.638-.7-1.738 0-1.05.813-1.713.812-.662 2.087-.662.575 0 1.063.087.487.088.837.288v-.35q0-.675-.462-1.075-.463-.4-1.263-.4-.525 0-.987.225-.463.225-.788.65l-1.075-.8q.475-.675 1.2-1.025t1.675-.35q1.55 0 2.375.738.825.737.825 2.137v4.4H18.55v-.85h-.075q-.325.5-.875.788-.55.287-1.25.287m.25-1.25q.8 0 1.363-.562t.562-1.363q-.35-.2-.8-.3t-.825-.1q-.8 0-1.225.313-.425.312-.425.887 0 .5.375.812t.975.313" /></SvgIcon>;
export default CaseIcon;