// autogenerated from icon svg file "icons/Regexp.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const RegexpIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M4.925 19.075q-1.4-1.425-2.162-3.25Q2 14 2 12t.75-3.825 2.175-3.25L6.35 6.35Q5.2 7.475 4.6 8.938 4 10.4 4 12t.612 3.063T6.35 17.65ZM9.5 18.05q-.625 0-1.062-.437Q8 17.175 8 16.55t.438-1.062T9.5 15.05t1.063.438T11 16.55t-.437 1.063-1.063.437m3.475-5v-1.775l-1.525.9-1-1.75 1.525-.875-1.525-.875 1-1.75 1.525.9V6.05h2v1.775l1.525-.9 1 1.75-1.525.875 1.525.875-1 1.75-1.525-.9v1.775zm6.1 6.025L17.65 17.65q1.15-1.125 1.75-2.587T20 12t-.613-3.062T17.65 6.35l1.425-1.425q1.4 1.425 2.163 3.25T22 12t-.75 3.825-2.175 3.25" /></SvgIcon>;
export default RegexpIcon;