// autogenerated from icon svg file "icons/RoutingEtc.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const RoutingEtcIcon = (props: SvgIconProps) => <SvgIcon {...props}><path fill="none" d="M0 0h24v24H0z" /><path d="M11.99 3A9 9 0 0 0 3 12a9 9 0 0 0 9 9 9 9 0 0 0 9-9 9 9 0 0 0-9-9zm-.084 2H12a7 7 0 0 1 7 7 7 7 0 0 1-7 7 7 7 0 0 1-7-7 7 7 0 0 1 6.906-7M11 7v1h-1l2 2 2-2h-1V7zm-2 3-2 2 2 2v-1h1v-2H9zm6 0v1h-1v2h1v1l2-2zm-3 4-2 2h1v1h2v-1h1z" /></SvgIcon>;
export default RoutingEtcIcon;