// autogenerated from icon svg file "icons/RoutingEtc.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const RoutingEtcIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M0 0h24v24H0V0z" fill="none" /><path d="M11.99 3A9 9 0 003 12a9 9 0 009 9 9 9 0 009-9 9 9 0 00-9-9 9 9 0 00-.01 0zm-.084 2A7 7 0 0112 5a7 7 0 017 7 7 7 0 01-7 7 7 7 0 01-7-7 7 7 0 016.906-7zM11 7v1h-1l2 2 2-2h-1V7h-2zm-2 3l-2 2 2 2v-1h1v-2H9v-1zm6 0v1h-1v2h1v1l2-2-2-2zm-3 4l-2 2h1v1h2v-1h1l-2-2z" /></SvgIcon>;
export default RoutingEtcIcon;