// autogenerated from icon svg file "icons/operstates/Dormant.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const DormantIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M6 3v2h12V3H6zm6 2l-6 6h12l-6-6zm0 2.828L13.172 9h-2.344L12 7.828z" /></SvgIcon>;
export default DormantIcon;