// autogenerated from icon svg file "icons/operstates/Dormant.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const DormantIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M6 3v2h6 6V3h-6zm6 2-6 6h12zm0 2.828L13.172 9h-2.344z" /></SvgIcon>;
export default DormantIcon;