// autogenerated from icon svg file "icons/operstates/Down.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const DownIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="m6 13 6 6 6-6zm6 6H6v2h6 6v-2zm-1.172-4h2.344L12 16.172z" /></SvgIcon>;
export default DownIcon;