// autogenerated from icon svg file "icons/operstates/Down.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const DownIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M6 13l6 6 6-6H6zm6 6H6v2h12v-2h-6zm-1.172-4h2.344L12 16.172 10.828 15z" /></SvgIcon>;
export default DownIcon;