// autogenerated from icon svg file "icons/operstates/LowerLayerDown.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const LowerLayerDownIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="m6 6 6 6 6-6zm6 6H6l6 6 6-6zm0 6H6v2h6 6v-2zM10.828 8h2.344L12 9.172zm0 6h2.344L12 15.172z" /></SvgIcon>;
export default LowerLayerDownIcon;