// autogenerated from icon svg file "icons/operstates/LowerLayerDown.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const LowerLayerDownIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M6 6l6 6 6-6H6zm6 6H6l6 6 6-6h-6zm0 6H6v2h12v-2h-6zM10.828 8h2.344L12 9.172 10.828 8zm0 6h2.344L12 15.172 10.828 14z" /></SvgIcon>;
export default LowerLayerDownIcon;