// autogenerated from icon svg file "icons/operstates/Unknown.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const UnknownIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 3L6 9h12l-6-6zm0 2.828L13.172 7h-2.344L12 5.828zM6 15l6 6 6-6H6zm4.828 2h2.344L12 18.172 10.828 17z" /></SvgIcon>;
export default UnknownIcon;