// autogenerated from icon svg file "icons/operstates/Unknown.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const UnknownIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 3 6 9h12zm0 2.828L13.172 7h-2.344zM6 15l6 6 6-6zm4.828 2h2.344L12 18.172z" /></SvgIcon>;
export default UnknownIcon;