// autogenerated from icon svg file "icons/operstates/Up.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const UpIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M6 3v2h6 6V3zm6 2-6 6h12z" /></SvgIcon>;
export default UpIcon;