// autogenerated from icon svg file "icons/operstates/Up.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const UpIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M6 3v2h12V3H6zm6 2l-6 6h12l-6-6z" /></SvgIcon>;
export default UpIcon;