// autogenerated from icon svg file "icons/routes/DirectSubnetRoute.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const DirectSubnetRouteIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 2A10 10 0 002 12a10 10 0 0010 10 10 10 0 0010-10A10 10 0 0012 2zm0 2a8 8 0 018 8 8 8 0 01-8 8 8 8 0 01-8-8 8 8 0 018-8zm-.05 5A3 3 0 009 12a3 3 0 003 3 3 3 0 003-3 3 3 0 00-3-3 3 3 0 00-.05 0z" /></SvgIcon>;
export default DirectSubnetRouteIcon;