// autogenerated from icon svg file "icons/routes/DirectSubnetRoute.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const DirectSubnetRouteIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 2A10 10 0 0 0 2 12a10 10 0 0 0 10 10 10 10 0 0 0 10-10A10 10 0 0 0 12 2zm0 2a8 8 0 0 1 8 8 8 8 0 0 1-8 8 8 8 0 0 1-8-8 8 8 0 0 1 8-8zm-.05 5A3 3 0 0 0 9 12a3 3 0 0 0 3 3 3 3 0 0 0 3-3 3 3 0 0 0-3-3z" /></SvgIcon>;
export default DirectSubnetRouteIcon;