// autogenerated from icon svg file "icons/routes/HostRoute.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const HostRouteIcon = (props: SvgIconProps) => <SvgIcon {...props}><circle cx={12} cy={12} r={3} /></SvgIcon>;
export default HostRouteIcon;