// autogenerated from icon svg file "icons/routes/NoRoute.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const NoRouteIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 2A10 10 0 002 12a10 10 0 0010 10 10 10 0 0010-10A10 10 0 0012 2zm0 2a8 8 0 014.902 1.688L12 10.59 7.094 5.684A8 8 0 0112 4zm6.316 3.094A8 8 0 0120 12a8 8 0 01-1.688 4.902L13.41 12l4.906-4.906zm-12.628.004L10.59 12l-4.906 4.906A8 8 0 014 12a8 8 0 011.688-4.902zM12 13.41l4.906 4.906A8 8 0 0112 20a8 8 0 01-4.902-1.688L12 13.41z" /></SvgIcon>;
export default NoRouteIcon;