// autogenerated from icon svg file "icons/routes/RouteVia.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const RouteViaIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 8a8 8 0 00-7.928 7H6.09A6 6 0 0112 10a6 6 0 014.24 1.76L14 14h6V8l-2.346 2.346A8 8 0 0012 8z" fillRule="evenodd" /></SvgIcon>;
export default RouteViaIcon;