// autogenerated from icon svg file "icons/groups/AppProject.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const AppProjectIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M11.178-6.5h13v13h-13z" transform="rotate(45)" /></SvgIcon>;
export default AppProjectIcon;