// autogenerated from icon svg file "icons/groups/AppProject.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const AppProjectIcon = (props: SvgIconProps) => <SvgIcon {...props}><path fillRule="evenodd" d="M12.5 3.308l9.193 9.192-9.193 9.193L3.308 12.5z" /></SvgIcon>;
export default AppProjectIcon;