// autogenerated from icon svg file "icons/containees/Netns.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const NetnsIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 2h14v14H5zm4 2v6h2v3c0 .554.446 1 1 1s1-.446 1-1v-3h2V7zm2 1h2v2.852h-2z" /></SvgIcon>;
export default NetnsIcon;