// autogenerated from icon svg file "icons/views/Details.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const DetailsIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 3c-1.108 0-2 .892-2 2v3c0 1.108.892 2 2 2h3c1.108 0 2-.892 2-2V5c0-1.108-.892-2-2-2H5zm7 0v2h8V3h-8zM5 5h3v3H5V5zm7 2v2h9V7h-9zm-7 6c-1.108 0-2 .892-2 2v3c0 1.108.892 2 2 2h3c1.108 0 2-.892 2-2v-3c0-1.108-.892-2-2-2H5zm7 0v2h8v-2h-8zm-7 2h3v3H5v-3zm7 2v2h9v-2h-9z" /></SvgIcon>;
export default DetailsIcon;