// autogenerated from icon svg file "icons/views/OpenHouse.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const OpenHouseIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 3 4 9v5.5a2.25 2.25 0 0 1 2.25 2.25A2.25 2.25 0 0 1 4 19v2h6v-7h4v7h2.09a1.5 1.5 0 0 1-.09-.5 1.5 1.5 0 0 1 1.5-1.5 1.5 1.5 0 0 1 1.5 1.5 1.5 1.5 0 0 1-.09.5H20v-5.883a2.25 2.25 0 0 1-1.25.383 2.25 2.25 0 0 1-2.25-2.25A2.25 2.25 0 0 1 18.75 11a2.25 2.25 0 0 1 1.25.379V9zM9.5 6.5A1.5 1.5 0 0 1 11 8a1.5 1.5 0 0 1-1.5 1.5A1.5 1.5 0 0 1 8 8a1.5 1.5 0 0 1 1.5-1.5" /></SvgIcon>;
export default OpenHouseIcon;