// autogenerated from icon svg file "icons/views/OpenHouse.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const OpenHouseIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 3L4 9v5.5a2.25 2.25 0 012.25 2.25A2.25 2.25 0 014 19v2h6v-7h4v7h2.09a1.5 1.5 0 01-.09-.5 1.5 1.5 0 011.5-1.5 1.5 1.5 0 011.5 1.5 1.5 1.5 0 01-.09.5H20v-5.883a2.25 2.25 0 01-1.25.383 2.25 2.25 0 01-2.25-2.25A2.25 2.25 0 0118.75 11a2.25 2.25 0 011.25.379V9l-8-6zM9.5 6.5A1.5 1.5 0 0111 8a1.5 1.5 0 01-1.5 1.5A1.5 1.5 0 018 8a1.5 1.5 0 011.5-1.5z" /></SvgIcon>;
export default OpenHouseIcon;