// autogenerated from icon svg file "icons/views/Wiring.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const WiringIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M13 3c-1.108 0-2 .892-2 2v3c0 .178.03.348.074.512l-2.562 2.562A2 2 0 0 0 8 11H5c-1.108 0-2 .892-2 2v3c0 1.108.892 2 2 2h3c.98 0 1.788-.698 1.963-1.625L14 17.721V19c0 1.108.892 2 2 2h3c1.108 0 2-.892 2-2v-3c0-1.108-.892-2-2-2h-3c-.98 0-1.788.698-1.963 1.625L10 14.279V13c0-.178-.03-.348-.074-.512l2.562-2.562c.164.043.334.074.512.074h3c1.108 0 2-.892 2-2V5c0-1.108-.892-2-2-2zm0 2h3v3h-3zm-8 8h3v3H5zm11 3h3v3h-3z" /></SvgIcon>;
export default WiringIcon;