# requires docker compose plugin (=v2)
#
# wget -q -O - https://github.com/siemens/ghostwire/raw/main/deployments/wget/docker-compose.yaml | docker compose -f - up
name: lxkns
services:
    gostwire:
        image: ghcr.io/siemens/ghostwire
        read_only: true
        entrypoint:
        - "/gostwire"
        - "--debug"
        - "--http"
        - "[::]:5000"
        ports:
        - "5000:5000"
        user: "65534"
        security_opt:
            - apparmor:unconfined #- apparmor:gostwire # only accepts profile name, not a profile file :(
        # In order to set only exactly a specific set of capabilities without
        # any additional Docker container default capabilities, we need to drop
        # "all" capabilities. Regardless of the order (there ain't one) of YAML
        # dictionary keys, Docker carries out dropping all capabilities first,
        # and only then adds capabilities. See also:
        # https://stackoverflow.com/a/63219871.
        cap_drop:
            - ALL
        cap_add:
            - SYS_ADMIN       # change namespaces
            - SYS_CHROOT      # change mount namespaces
            - SYS_PTRACE      # access nsfs namespace information
            - DAC_READ_SEARCH # access/scan /proc/[$PID]/fd itself
            - DAC_OVERRIDE    # access container engine unix domain sockets without being rude, erm, root.
            - NET_RAW         # pingin' 'round
            - NET_ADMIN       # readin' more than enough tables...
        # Essential since we need full PID view.
        pid: host
        networks:
            00-default:
                priority: 200
            99-ghost-in-da-box:
                priority: 100
networks:
    # this is the usual the project's default network, for which ports can be
    # exposed.
    00-default:
       name: gostwire_default
    # host-internal network without any exposed ports.
    99-ghost-in-da-box:
       name: ghost-in-da-box
       internal: true
